export default {
  port: 'PORT',
  nodeEnv: 'NODE_ENV',
  host: 'HOST',
  apiVersion: 'API_VERSION',
  logLevel: 'LOG_LEVEL',
  dbUri: 'DB_URI',
  redisHost: 'REDIS_HOST',
  redisPort: 'REDIS_PORT',
  redisUsername: 'REDIS_USERNAME',
  redisPassword: 'REDIS_PASSWORD',
  openaiApiKey: 'OPENAI_API_KEY',
  openaiBaseUrl: 'OPENAI_BASE_URL',
  geminiApiKey: 'GEMINI_API_KEY',
  geminiBaseUrl: 'GEMINI_BASE_URL',
};
